services:
  - type: web
    name: nilaundry
    env: php
    buildCommand: |-
      composer install --no-dev --optimize-autoloader &&
      npm ci &&
      npm run build &&
      php artisan optimize
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:D3OUJ8QLQqtU9Wjs4/j5KXSrxnyl4JysnOVKLShsD54=
      - key: APP_URL
        value: https://nilaundry.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
